import Header from "./Header";
import Head from "next/head";
import Body from "./Body";
import Projects from "./Projects";
import ContactForm from "./ContactForm";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio -FrontEnd Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/iconnew.png" />
      </Head>
      <main className="">
        <Header />
        <Body />
        <Projects />
        <ContactForm />
        <Footer />
      </main>
    </>
  );
}
